# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TimePickerDialog.ui'
#
# Created: Tue May  5 12:38:32 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TimePickerDialog(object):
    def setupUi(self, TimePickerDialog):
        TimePickerDialog.setObjectName(_fromUtf8("TimePickerDialog"))
        TimePickerDialog.resize(770, 290)
        TimePickerDialog.setMinimumSize(QtCore.QSize(770, 290))
        TimePickerDialog.setMaximumSize(QtCore.QSize(770, 300))
        TimePickerDialog.setStyleSheet(_fromUtf8("background: rgb(84, 84, 84)"))
        self.hour_button_08 = QtGui.QPushButton(TimePickerDialog)
        self.hour_button_08.setGeometry(QtCore.QRect(530, 80, 51, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hour_button_08.setFont(font)
        self.hour_button_08.setStyleSheet(_fromUtf8("color: white;"))
        self.hour_button_08.setObjectName(_fromUtf8("hour_button_08"))
        self.hour_button_09 = QtGui.QPushButton(TimePickerDialog)
        self.hour_button_09.setGeometry(QtCore.QRect(590, 80, 51, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hour_button_09.setFont(font)
        self.hour_button_09.setStyleSheet(_fromUtf8("color: white;"))
        self.hour_button_09.setObjectName(_fromUtf8("hour_button_09"))
        self.am_button = QtGui.QPushButton(TimePickerDialog)
        self.am_button.setGeometry(QtCore.QRect(10, 5, 241, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.am_button.setFont(font)
        self.am_button.setStyleSheet(_fromUtf8("color: white;"))
        self.am_button.setObjectName(_fromUtf8("am_button"))
        self.pm_button = QtGui.QPushButton(TimePickerDialog)
        self.pm_button.setGeometry(QtCore.QRect(500, 5, 261, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pm_button.setFont(font)
        self.pm_button.setStyleSheet(_fromUtf8("color: white;"))
        self.pm_button.setObjectName(_fromUtf8("pm_button"))
        self.hour_button_10 = QtGui.QPushButton(TimePickerDialog)
        self.hour_button_10.setGeometry(QtCore.QRect(650, 80, 51, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hour_button_10.setFont(font)
        self.hour_button_10.setStyleSheet(_fromUtf8("color: white;"))
        self.hour_button_10.setObjectName(_fromUtf8("hour_button_10"))
        self.hour_button_11 = QtGui.QPushButton(TimePickerDialog)
        self.hour_button_11.setGeometry(QtCore.QRect(710, 80, 51, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hour_button_11.setFont(font)
        self.hour_button_11.setStyleSheet(_fromUtf8("color: white;"))
        self.hour_button_11.setObjectName(_fromUtf8("hour_button_11"))
        self.hour_button_01 = QtGui.QPushButton(TimePickerDialog)
        self.hour_button_01.setGeometry(QtCore.QRect(100, 80, 51, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hour_button_01.setFont(font)
        self.hour_button_01.setStyleSheet(_fromUtf8("color: white;"))
        self.hour_button_01.setObjectName(_fromUtf8("hour_button_01"))
        self.hour_button_02 = QtGui.QPushButton(TimePickerDialog)
        self.hour_button_02.setGeometry(QtCore.QRect(160, 80, 51, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hour_button_02.setFont(font)
        self.hour_button_02.setStyleSheet(_fromUtf8("color: white;"))
        self.hour_button_02.setObjectName(_fromUtf8("hour_button_02"))
        self.hour_button_03 = QtGui.QPushButton(TimePickerDialog)
        self.hour_button_03.setGeometry(QtCore.QRect(220, 80, 51, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hour_button_03.setFont(font)
        self.hour_button_03.setStyleSheet(_fromUtf8("color: white;"))
        self.hour_button_03.setObjectName(_fromUtf8("hour_button_03"))
        self.hour_button_04 = QtGui.QPushButton(TimePickerDialog)
        self.hour_button_04.setGeometry(QtCore.QRect(280, 80, 51, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hour_button_04.setFont(font)
        self.hour_button_04.setStyleSheet(_fromUtf8("color: white;"))
        self.hour_button_04.setObjectName(_fromUtf8("hour_button_04"))
        self.hour_button_05 = QtGui.QPushButton(TimePickerDialog)
        self.hour_button_05.setGeometry(QtCore.QRect(340, 80, 51, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hour_button_05.setFont(font)
        self.hour_button_05.setStyleSheet(_fromUtf8("color: white;"))
        self.hour_button_05.setObjectName(_fromUtf8("hour_button_05"))
        self.hour_button_06 = QtGui.QPushButton(TimePickerDialog)
        self.hour_button_06.setGeometry(QtCore.QRect(400, 80, 51, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hour_button_06.setFont(font)
        self.hour_button_06.setStyleSheet(_fromUtf8("color: white;"))
        self.hour_button_06.setObjectName(_fromUtf8("hour_button_06"))
        self.minute_button_00 = QtGui.QPushButton(TimePickerDialog)
        self.minute_button_00.setGeometry(QtCore.QRect(280, 150, 51, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.minute_button_00.setFont(font)
        self.minute_button_00.setStyleSheet(_fromUtf8("color: white;"))
        self.minute_button_00.setObjectName(_fromUtf8("minute_button_00"))
        self.minute_button_15 = QtGui.QPushButton(TimePickerDialog)
        self.minute_button_15.setGeometry(QtCore.QRect(340, 150, 51, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.minute_button_15.setFont(font)
        self.minute_button_15.setStyleSheet(_fromUtf8("color: white;"))
        self.minute_button_15.setObjectName(_fromUtf8("minute_button_15"))
        self.minute_button_30 = QtGui.QPushButton(TimePickerDialog)
        self.minute_button_30.setGeometry(QtCore.QRect(400, 150, 51, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.minute_button_30.setFont(font)
        self.minute_button_30.setStyleSheet(_fromUtf8("color: white;"))
        self.minute_button_30.setObjectName(_fromUtf8("minute_button_30"))
        self.minute_button_45 = QtGui.QPushButton(TimePickerDialog)
        self.minute_button_45.setGeometry(QtCore.QRect(460, 150, 51, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.minute_button_45.setFont(font)
        self.minute_button_45.setStyleSheet(_fromUtf8("color: white;"))
        self.minute_button_45.setObjectName(_fromUtf8("minute_button_45"))
        self.hour_button_12 = QtGui.QPushButton(TimePickerDialog)
        self.hour_button_12.setGeometry(QtCore.QRect(10, 80, 51, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hour_button_12.setFont(font)
        self.hour_button_12.setStyleSheet(_fromUtf8("color: white;"))
        self.hour_button_12.setObjectName(_fromUtf8("hour_button_12"))
        self.line = QtGui.QFrame(TimePickerDialog)
        self.line.setGeometry(QtCore.QRect(10, 60, 751, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.cancel_button = QtGui.QPushButton(TimePickerDialog)
        self.cancel_button.setGeometry(QtCore.QRect(230, 230, 151, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cancel_button.setFont(font)
        self.cancel_button.setStyleSheet(_fromUtf8("color: white;"))
        self.cancel_button.setObjectName(_fromUtf8("cancel_button"))
        self.ok_button = QtGui.QPushButton(TimePickerDialog)
        self.ok_button.setGeometry(QtCore.QRect(400, 230, 161, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ok_button.setFont(font)
        self.ok_button.setStyleSheet(_fromUtf8("color: white;"))
        self.ok_button.setObjectName(_fromUtf8("ok_button"))
        self.hour_button_07 = QtGui.QPushButton(TimePickerDialog)
        self.hour_button_07.setGeometry(QtCore.QRect(460, 80, 51, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hour_button_07.setFont(font)
        self.hour_button_07.setStyleSheet(_fromUtf8("color: white;"))
        self.hour_button_07.setObjectName(_fromUtf8("hour_button_07"))
        self.line_2 = QtGui.QFrame(TimePickerDialog)
        self.line_2.setGeometry(QtCore.QRect(10, 210, 751, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label1 = QtGui.QLabel(TimePickerDialog)
        self.label1.setGeometry(QtCore.QRect(320, 20, 121, 21))
        self.label1.setStyleSheet(_fromUtf8("color: white;"))
        self.label1.setObjectName(_fromUtf8("label1"))

        self.retranslateUi(TimePickerDialog)
        QtCore.QMetaObject.connectSlotsByName(TimePickerDialog)

    def retranslateUi(self, TimePickerDialog):
        TimePickerDialog.setWindowTitle(_translate("TimePickerDialog", "Dialog", None))
        self.hour_button_08.setText(_translate("TimePickerDialog", "08", None))
        self.hour_button_09.setText(_translate("TimePickerDialog", "09", None))
        self.am_button.setText(_translate("TimePickerDialog", "MORNING ( AM )", None))
        self.pm_button.setText(_translate("TimePickerDialog", "AFTERNOON-NIGHT ( PM )", None))
        self.hour_button_10.setText(_translate("TimePickerDialog", "10", None))
        self.hour_button_11.setText(_translate("TimePickerDialog", "11", None))
        self.hour_button_01.setText(_translate("TimePickerDialog", "01", None))
        self.hour_button_02.setText(_translate("TimePickerDialog", "02", None))
        self.hour_button_03.setText(_translate("TimePickerDialog", "03", None))
        self.hour_button_04.setText(_translate("TimePickerDialog", "04", None))
        self.hour_button_05.setText(_translate("TimePickerDialog", "05", None))
        self.hour_button_06.setText(_translate("TimePickerDialog", "06", None))
        self.minute_button_00.setText(_translate("TimePickerDialog", "00", None))
        self.minute_button_15.setText(_translate("TimePickerDialog", "15", None))
        self.minute_button_30.setText(_translate("TimePickerDialog", "30", None))
        self.minute_button_45.setText(_translate("TimePickerDialog", "45", None))
        self.hour_button_12.setText(_translate("TimePickerDialog", "12", None))
        self.cancel_button.setText(_translate("TimePickerDialog", "CANCEL", None))
        self.ok_button.setText(_translate("TimePickerDialog", "OK", None))
        self.hour_button_07.setText(_translate("TimePickerDialog", "07", None))
        self.label1.setText(_translate("TimePickerDialog", "<html><head/><body><p>Select AM or PM</p></body></html>", None))

